version: '3.4'

services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: table-structure-sample:0.0.3
    tmpfs:
      - /tmp

  rails:
    <<: *app
    volumes:
      - ./rails:/app:cached
      - ./table_structures:/app/app/table_structures:cached
      - rails_cache:/app/tmp/cache
      - rails_node_modules:/app/node_modules
      - bundle:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql:8
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

volumes:
  mysql:
  bundle:
  rails_cache:
  rails_node_modules:
